# Generated by Django 4.0.1 on 2022-05-26 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fraud_detection', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='linkstoreview',
            name='rating_number',
        ),
        migrations.RemoveField(
            model_name='linkstoreview',
            name='review',
        ),
        migrations.AddField(
            model_name='userreviewed',
            name='rate',
            field=models.DecimalField(blank=True, decimal_places=3, default=1, max_digits=4),
        ),
        migrations.AlterField(
            model_name='userreviewed',
            name='review',
            field=models.TextField(),
        ),
    ]
