# Generated by Django 4.0.1 on 2022-05-26 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fraud_detection', '0002_remove_linkstoreview_rating_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userreviewed',
            name='sentiment_analysis',
            field=models.CharField(default='', max_length=10),
        ),
    ]
